version: '3'

services:

  database:
    image: mysql:5.6
    restart: always
    volumes:
      - ./raw_cr.sql:/docker-entrypoint-initdb.d/raw_cr.sql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: raw_cr
    expose:
      - 3306

  default-cr:
    restart: always
    build: .
    image: default-cr
    command: ["gunicorn", "-b", "0.0.0.0:8000", "--worker-class", "gthread", "-w", "1", "--threads", "1", "app:app"]
    depends_on:
      - database
    links:
      - database
    expose: 
      - 8000
      - 443

  server:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - default-cr
    links:
      - default-cr:default-cr
    ports:
      - "80:80"
